version: "3.8"
services:
  db-catalogo:
    image: mysql:8.0.30
    container_name: "db-catalogo"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_catalogo
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10

  api-catalogo:
    build: .
    container_name: "api-catalogo"
    depends_on:
      db-catalogo:
        condition: service_healthy
    ports:
      - "8084:8081"
    networks:
      - app_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-catalogo:3306/db_catalogo?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

networks:
  app_network:
    driver: bridge
