version: "3.8"
services:
  db:
    image: mysql:8.0.30
    container_name: "db-pedidos"
    environment:
      MYSQL_ROOT_PASSWORD: adminroot
      MYSQL_DATABASE: db_pedidos
    ports:
      - "3310:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app_network
  api:
    build: .
    container_name: "api-pedidos"
    depends_on:
      - db
    ports:
      - "8082:8081"
    networks:
      - app_network

  

networks:
  app_network:
    driver: bridge
