version: '3.8'

services:
  api:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-usuario:3306/usuarios?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - usuario-network

  db:
    container_name: db-usuario
    image: mysql:8.0.30
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=usuarios
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - usuario-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  usuario-network:
    driver: bridge

volumes:
  mysql-data:
