version: "3.8"
services:
  db:
    image: mysql:8.0.30
    container_name: "db-usuario"
    environment:
      MYSQL_ROOT_PASSWORD: adminroot
      MYSQL_DATABASE: db_usuario
    ports:
      - "3311:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app_network
  api:
    build: .
    container_name: "api-usuario"
    depends_on:
      - db
    ports:
      - "8083:8081"
    networks:
      - app_network

  

networks:
  app_network:
    driver: bridge
